server:
  port: 8081

bot:
  log:
    level: info
  excute:
    interval: 2

network:
  # 代理配置
  proxy:
    enabled: true
    host: 10.17.145.201
    port: 1080
  # 接口配置
  remote:
    openocean:
      apiV2Url: https://openapi-test.openocean.finance




